image: registry.gitlab.com/liquiduniverse/docgen:latest

stages:
   # build 
   # build-core
   #- test
   #- test-core
   - pages
   - update-parent

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

#build:
  #stage: build
  #script:
     #- dotnet build
  #artifacts:
     #paths:
      # - ./build/

#build-core:
  #stage: build-core
  #script:
     #- dotnet build
  #artifacts:
     #paths:
       #- ./build/

#test:
   #stage: test
   #script:
      #- dotnet test AtomicMarketApiClient.Test/AtomicMarketApiClient.Test.csproj
  
#test-core:
   #stage: test-core
   #script:
      #- dotnet test AtomicMarketApiClient.Core.Test/AtomicMarketApiClient.Core.Test.csproj

pages:
   stage: pages
   script:
      - doxygen documentation/doxygen/Doxyfile
      - doxybook2 --input  documentation/doxyoutput/xml --output  documentation/gitbook --config documentation/doxybook-config/gitbook/.doxybook/config.json --summary-input documentation/doxybook-config/gitbook/SUMMARY.md.tmpl --summary-output documentation/gitbook/SUMMARY.md 
    
      - gitbook build documentation/gitbook documentation/gitbook_output
      - cp -r documentation/gitbook_output public
   artifacts:
      paths:
         - public
         - documentation
       
    
update-parent:
  stage: update-parent
  script:
   
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
    - git clone -b corvin https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.com/liquiduniverse/unityeosclientplugins/theliquiidbible_gitbook.git /parent 
    - cp -r documentation/gitbook /parent/atomicmarketapiclient/
    - cd /parent
    - git add .
    - git commit -m "${COMMIT_MESSAGE}"
    - git push
    
